'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ShareRibbon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property aiapiconfig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aiapiconfig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property aiwrite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aiwrite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property audit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property chat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * chat-manager.js - Chat Section Management
        ''' * Functions for creating and managing chat message sections
        ''' */
        '''
        '''// Create chat section with sender info and content area
        '''window.createChatSection = function (sender, timestamp, uuid) {
        '''    // Create chat container
        '''    const chatContainer = document.createElement(&apos;div&apos;);
        '''    chatContainer.className = &apos;chat-container&apos;;
        '''    chatContainer.id = &apos;chat-&apos; + uuid;
        '''
        '''    // Record sender for later reference
        '''    chatContainer.dataset.sender = sender;
        '''
        '''   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property chat_manager() As String
            Get
                Return ResourceManager.GetString("chat_manager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;zh-CN&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''    &lt;title&gt;AI Chat&lt;/title&gt;
        '''    &lt;!-- Third-party libraries - using virtual host officeai.local --&gt;
        '''    &lt;script src=&quot;https://officeai.local/js/marked.min.js&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;https://officeai.local/js/highlight.min.js&quot;&gt;&lt;/script&gt;
        '''    &lt;script src=&quot;https://officeai.local/js/vbscript.min.js&quot;&gt;&lt;/script&gt;
        '''    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://officeai. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property chat_template_refactored() As String
            Get
                Return ResourceManager.GetString("chat_template_refactored", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * code-handler.js - Code Block Handling
        ''' * Functions for copying, executing, and editing code blocks
        ''' */
        '''
        '''/**
        ''' * 隐藏指定消息中代码块的编辑和执行按钮（校对/排版模式使用）
        ''' * @param {string} uuid - 消息的UUID
        ''' */
        '''function hideCodeActionButtons(uuid) {
        '''    const messageContainer = document.getElementById(&apos;content-&apos; + uuid);
        '''    if (!messageContainer) return;
        '''    
        '''    // 隐藏所有编辑和执行按钮，只保留复制按钮
        '''    const editButtons = messageContainer.querySelectorAll(&apos;.edit-button&apos;);
        '''    const executeButtons = messageContainer.querySelector [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property code_handler() As String
            Get
                Return ResourceManager.GetString("code_handler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * core.js - Core initialization for OfficeAI Chat
        ''' * Marked.js configuration and renderer setup
        ''' */
        '''
        '''// Configure marked.js
        '''marked.setOptions({
        '''    highlight: function (code, lang) {
        '''        if (lang &amp;&amp; hljs.getLanguage(lang)) {
        '''            return hljs.highlight(code, { language: lang }).value;
        '''        }
        '''        return hljs.highlightAuto(code).value;
        '''    },
        '''    breaks: true,
        '''    gfm: true
        '''});
        '''
        '''// Extend marked renderer for code blocks with action buttons
        '''const renderer = new marked.Re [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property core() As String
            Get
                Return ResourceManager.GetString("core", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property deepseek() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deepseek", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property doubao_avatar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doubao_avatar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 pre code.hljs{display:block;overflow-x:auto;padding:1em}code.hljs{padding:3px 5px}/*!
        '''  Theme: GitHub
        '''  Description: Light theme as seen on github.com
        '''  Author: github.com
        '''  Maintainer: @Hirse
        '''  Updated: 2021-05-15
        '''
        '''  Outdated base version: https://github.com/primer/github-syntax-light
        '''  Current colors taken from GitHub&apos;s CSS
        '''*/.hljs{color:#24292e;background:#fff}.hljs-doctag,.hljs-keyword,.hljs-meta .hljs-keyword,.hljs-template-tag,.hljs-template-variable,.hljs-type,.hljs-variable.language_{color:#d73a49}. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property github_min() As String
            Get
                Return ResourceManager.GetString("github_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /*!
        '''  Highlight.js v11.7.0 (git: 82688fad18)
        '''  (c) 2006-2022 undefined and other contributors
        '''  License: BSD-3-Clause
        ''' */
        '''var hljs=function(){&quot;use strict&quot;;var e={exports:{}};function n(e){
        '''return e instanceof Map?e.clear=e.delete=e.set=()=&gt;{
        '''throw Error(&quot;map is read-only&quot;)}:e instanceof Set&amp;&amp;(e.add=e.clear=e.delete=()=&gt;{
        '''throw Error(&quot;set is read-only&quot;)
        '''}),Object.freeze(e),Object.getOwnPropertyNames(e).forEach((t=&gt;{var a=e[t]
        ''';&quot;object&quot;!=typeof a||Object.isFrozen(a)||n(a)})),e}
        '''e.exports=n,e.exports.default=n [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property highlight_min() As String
            Get
                Return ResourceManager.GetString("highlight_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * history-manager.js - History Sidebar and File Management
        ''' * Handles chat history display and navigation
        ''' */
        '''
        '''window.historyManager = {
        '''    isOpen: false,
        '''
        '''    // Initialize history functionality
        '''    init: function () {
        '''        const toggleBtn = document.getElementById(&apos;history-toggle-btn&apos;);
        '''        const sidebar = document.getElementById(&apos;history-sidebar&apos;);
        '''        const overlay = document.getElementById(&apos;sidebar-overlay&apos;);
        '''        const closeBtn = document.getElementById(&apos;close-sidebar- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property history_manager() As String
            Get
                Return ResourceManager.GetString("history_manager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property magic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * markdown-renderer.js - Markdown Stream Renderer
        ''' * Handles incremental markdown rendering for streaming responses
        ''' */
        '''
        '''class MarkdownStreamRenderer {
        '''    constructor(element) {
        '''        this.output = element instanceof HTMLElement ? element : document.getElementById(element);
        '''        this.fullContent = &apos;&apos;;
        '''    }
        '''
        '''    append(text) {
        '''        this.fullContent += text + &apos;&apos;;
        '''
        '''        // Use full content render
        '''        this.output.innerHTML = marked.parse(this.fullContent);
        '''
        '''        // Appl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property markdown_renderer() As String
            Get
                Return ResourceManager.GetString("markdown_renderer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * marked v15.0.7 - a markdown parser
        ''' * Copyright (c) 2011-2025, Christopher Jeffrey. (MIT Licensed)
        ''' * https://github.com/markedjs/marked
        ''' */
        '''!function(e,t){&quot;object&quot;==typeof exports&amp;&amp;&quot;undefined&quot;!=typeof module?t(exports):&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;exports&quot;],t):t((e=&quot;undefined&quot;!=typeof globalThis?globalThis:e||self).marked={})}(this,(function(e){&quot;use strict&quot;;function t(){return{async:!1,breaks:!1,extensions:null,gfm:!0,hooks:null,pedantic:!1,renderer:null,silent:!1,tokenizer:null,wa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property marked_min() As String
            Get
                Return ResourceManager.GetString("marked_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * mcp-manager.js - MCP Connection Management
        ''' * Handles MCP (Model Context Protocol) connection display and configuration
        ''' */
        '''
        '''// MCP state variables
        '''let mcpConnections = [];
        '''let enabledMcpList = [];
        '''let mcpSupported = false;
        '''
        '''// Toggle MCP dialog visibility
        '''function toggleMcpDialog() {
        '''    requestMcpConnections();
        '''    document.getElementById(&apos;mcp-dialog&apos;).style.display = &apos;block&apos;;
        '''    document.getElementById(&apos;mcp-overlay&apos;).style.display = &apos;block&apos;;
        '''}
        '''
        '''// Close MCP dialog
        '''function close [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property mcp_manager() As String
            Get
                Return ResourceManager.GetString("mcp_manager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property mcp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mcp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * message-sender.js - Message Sending Logic
        ''' * Handles sending messages to backend and managing input UI
        ''' */
        '''
        '''// Send message payload to server (VB backend)
        '''function sendMessageToServer(messagePayload) {
        '''    if (window.chrome &amp;&amp; window.chrome.webview) {
        '''        window.chrome.webview.postMessage(messagePayload);
        '''    } else if (window.vsto) {
        '''        if (typeof window.vsto.sendMessage === &apos;function&apos;) {
        '''            if (messagePayload.type === &apos;sendMessage&apos; &amp;&amp; typeof messagePayload.value === &apos;ob [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property message_sender() As String
            Get
                Return ResourceManager.GetString("message_sender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property papers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("papers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * revision-manager.js - Revision Display and Application
        ''' * Handles document formatting preview and revision suggestions
        ''' */
        '''
        '''(function () {
        '''    if (!window._oa) window._oa = {};
        '''    window._oa._comparisonCache = window._oa._comparisonCache || {};
        '''
        '''    // Format preview (simplified: using paraIndex and formatting object)
        '''    window.showComparison = function (uuid, originalText, aiPreviewOrPlan) {
        '''        console.log(aiPreviewOrPlan);
        '''        try {
        '''            const container = document.get [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property revision_manager() As String
            Get
                Return ResourceManager.GetString("revision_manager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property send32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("send32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * settings-manager.js - Settings Dialog Management
        ''' * Handles settings dialog display, save, and cancel operations
        ''' */
        '''
        '''// Open settings dialog
        '''function settingsButton() {
        '''    document.getElementById(&apos;settings-overlay&apos;).style.display = &apos;block&apos;;
        '''    document.getElementById(&apos;settings-dialog&apos;).style.display = &apos;block&apos;;
        '''}
        '''
        '''// Cancel settings dialog
        '''function settingsCancel() {
        '''    document.getElementById(&apos;settings-overlay&apos;).style.display = &apos;none&apos;;
        '''    document.getElementById(&apos;settings-dialog&apos;). [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property settings_manager() As String
            Get
                Return ResourceManager.GetString("settings_manager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /* ShareRibbon/Resources/css/styles.css */
        '''/* Office AI Chat 样式表 - 从 chat-template.html 提取 */
        '''
        '''/* ====== 基础样式 ====== */
        '''body {
        '''    font-family: -apple-system, BlinkMacSystemFont, &apos;Segoe UI&apos;, Roboto, Oxygen, Ubuntu, Cantarell, &apos;Open Sans&apos;, &apos;Helvetica Neue&apos;, sans-serif;
        '''    line-height: 1.5;
        '''    color: #333;
        '''    max-width: 800px;
        '''    margin: 0 auto;
        '''    padding: 20px;
        '''    background-color: #f9f9f9;
        '''    padding-bottom: 160px;
        '''}
        '''
        '''#chat-output {
        '''    padding: 20px;
        '''    background-color: white;
        '''  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property styles() As String
            Get
                Return ResourceManager.GetString("styles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property translate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("translate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /**
        ''' * utils.js - Utility functions for OfficeAI Chat
        ''' * Common helper functions used across the application
        ''' */
        '''
        '''// Generate UUID v4
        '''function generateUUID() {
        '''    return &apos;xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx&apos;.replace(/[xy]/g, function (c) {
        '''        const r = Math.random() * 16 | 0;
        '''        const v = c === &apos;x&apos; ? r : (r &amp; 0x3 | 0x8);
        '''        return v.toString(16);
        '''    });
        '''}
        '''
        '''// Format date time to string
        '''function formatDateTime(date) {
        '''    const year = date.getFullYear();
        '''    const month = S [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property utils() As String
            Get
                Return ResourceManager.GetString("utils", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /*! `vbscript` grammar compiled for Highlight.js 11.7.0 */
        '''(()=&gt;{var e=(()=&gt;{&quot;use strict&quot;;return e=&gt;{
        '''const t=e.regex,r=[&quot;lcase&quot;,&quot;month&quot;,&quot;vartype&quot;,&quot;instrrev&quot;,&quot;ubound&quot;,&quot;setlocale&quot;,&quot;getobject&quot;,&quot;rgb&quot;,&quot;getref&quot;,&quot;string&quot;,&quot;weekdayname&quot;,&quot;rnd&quot;,&quot;dateadd&quot;,&quot;monthname&quot;,&quot;now&quot;,&quot;day&quot;,&quot;minute&quot;,&quot;isarray&quot;,&quot;cbool&quot;,&quot;round&quot;,&quot;formatcurrency&quot;,&quot;conversions&quot;,&quot;csng&quot;,&quot;timevalue&quot;,&quot;second&quot;,&quot;year&quot;,&quot;space&quot;,&quot;abs&quot;,&quot;clng&quot;,&quot;timeserial&quot;,&quot;fixs&quot;,&quot;len&quot;,&quot;asc&quot;,&quot;isempty&quot;,&quot;maths&quot;,&quot;dateserial&quot;,&quot;atn&quot;,&quot;timer&quot;,&quot;isobject&quot;,&quot;filter&quot;,&quot;weekday&quot;,&quot;datevalue&quot;,&quot;c [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property vbscript_min() As String
            Get
                Return ResourceManager.GetString("vbscript_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property wait() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wait", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
